### ISSUE TITLE
What am I doing wrong? I keep getting this error.

### ISSUE THREAD

**Issue by Pere-Upoko** [Tr4sHCr4fT/fastmap#10]
C:\Users\Josh\Desktop\fastmap-master>bootstrap.py -l "-38.690754, 176.081872" -r 9000
Traceback (most recent call last):
  File "C:\Users\Josh\Desktop\fastmap-master\bootstrap.py", line 22, in <module>
    from pgoapi.exceptions import NotLoggedInException
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "C:\Python27\lib\site-packages\pgoapi-1.1.6-py2.7.egg\pgoapi\auth_google.py", line 31, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

I think I have all the files in the right place. Not sure what I am doing wrong. Sorry. Bit new.

**Comment by tcmaps** [comment]
have you installed all requirements?  
on Windows you need to run 'pip install -r requirements' from an _elevated_ CMD  
also you need to download pgoapi and run 'setup.py install' (also as admin)
