### ISSUE TITLE
Error with empty data :(

### ISSUE THREAD

**Issue by omlet05** [Tr4sHCr4fT/fastmap#8]
hi, 
I try to use your project but I've got this issue:

```
~/fastmap$ python bootstrap.py -l "******** ****" -r 100
[ INFO] 31.08.16 00:28:25 DB created!
[ INFO] 31.08.16 00:28:25 Added 1 items to scan queue.
[ INFO] 31.08.16 00:28:25 DB loaded.
[ INFO] 31.08.16 00:28:25 Initializing worker  1 of  1
Traceback (most recent call last):
  File "bootstrap.py", line 288, in <module>
    main()
  File "bootstrap.py", line 134, in main
    api = api_init(accounts[m]); sleep(3)
  File "/home/omlet/fastmap/fastmap/apiwrap.py", line 33, in api_init
    api.activate_signature(get_encryption_lib_path()); time.sleep(1); api.get_player()
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 139, in function
    return request.call()
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 241, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/rpc_api.py", line 127, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/rpc_api.py", line 215, in _build_main_request
    for key in self.device_info:
TypeError: 'NoneType' object is not iterable

```

**Comment by Tr4sHCr4fT** [comment]
what version of pgoapi do you have and do you also got the magiclib/libencrypt.dll?

**Comment by tcmaps** [comment]
Ah, i see... this bug is from pgoapi itself, issue #118  
https://github.com/pogodevorg/pgoapi/issues/118

**Comment by omlet05** [comment]
nice ;)

## ~/fastmap$ pip show pgoapi

Metadata-Version: 1.1
Name: pgoapi
Version: 1.1.6
Summary: Pokemon Go API lib

**Comment by tcmaps** [comment]
you could change the lines:215..6 in rpc_api.py yourself,  
or just clone the latest pgoapi and do a clean reinstall :)

**Comment by omlet05** [comment]
thanks a lot !

good job men
